import type { Metadata } from "next";
import { Poppins, Playwrite_US_Modern } from "next/font/google";
import "./globals.css";
import Nav from "./(site)/_components/common/nav";
import Footer from "./(site)/_components/common/footer";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const playwrite = Playwrite_US_Modern({
  variable: "--font-playwrite",
  weight: ["100", "200", "300", "400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${playwrite.variable} antialiased`}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
